[line_break]
disabled = true

[cmd_duration]
disabled = true

[character] 
success_symbol = "[➜](bold green) "
error_symbol = "[✖](bold red)"

[hostname]
ssh_only = false
format =  "[$hostname](bold green) "
disabled = false

[kubernetes]
disabled = false

[git_branch]
symbol = " "

[aws]
disabled = false
symbol = " "
format = "on [$symbol$profile( \\($region\\))]($style) "
style = "bold yellow"
